---
version: 2

before:
  hooks:
    - go mod tidy
    - go test .
    - docker buildx create --name mybuilder --driver docker-container --use --bootstrap || docker buildx use mybuilder

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -X main.Version={{ .Version }}
    flags:
      - -trimpath

checksum:
  name_template: "checksums.txt"

archives:
  - formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - LICENSE
      - config.yaml.example

dockers_v2:
  - images:
      - "f100024/{{ .ProjectName }}"
    tags:
      - "v{{ .Version }}"
      - "latest"
    dockerfile: Dockerfile-gha
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    extra_files:
      - LICENSE
      - config.yaml.example
    sbom: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "merge conflict"
      - Merge pull request
      - Merge branch

release:
  draft: true
  replace_existing_draft: true
