---
version: 2

before:
  hooks:
    - go mod tidy
    - go test .
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -X main.Version={{ .Version }}
    flags:
      - -trimpath
checksum:
  name_template: "checksums.txt"


archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - config.yaml.example

dockers:
  - image_templates:
      - "f100024/{{ .ProjectName }}:v{{ .Version }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile-gha
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    extra_files:
      - LICENSE
      - config.yaml.example

  - image_templates:
    - "f100024/{{ .ProjectName }}:v{{ .Version }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile-gha
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--push=true"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    extra_files:
      - LICENSE
      - config.yaml.example

  - image_templates:
    - "f100024/{{ .ProjectName }}:v{{ .Version }}-armv7"
    use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile-gha
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--push=true"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    extra_files:
      - LICENSE
      - config.yaml.example

docker_manifests:
  - name_template: f100024/{{ .ProjectName }}:v{{ .Version }}
    image_templates:
      - f100024/{{ .ProjectName }}:v{{ .Version }}-amd64
      - f100024/{{ .ProjectName }}:v{{ .Version }}-arm64
      - f100024/{{ .ProjectName }}:v{{ .Version }}-armv7
  - name_template: f100024/{{ .ProjectName }}:latest
    image_templates:
      - f100024/{{ .ProjectName }}:v{{ .Version }}-amd64
      - f100024/{{ .ProjectName }}:v{{ .Version }}-arm64
      - f100024/{{ .ProjectName }}:v{{ .Version }}-armv7

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "merge conflict"
      - Merge pull request
      - Merge branch

release:
  draft: true
  replace_existing_draft: true
